// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using incidenskezelo_backend.Data;

#nullable disable

namespace incidenskezelo_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003165725_AddServicesAndEvents")]
    partial class AddServicesAndEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("incidenskezelo_backend.Models.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EventId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SourceEventId")
                        .IsUnique();

                    b.ToTable("Event", null, t =>
                        {
                            t.HasCheckConstraint("CK_Event_EventType", "[EventType] IN ('ServiceDown', 'ServiceRecovered', 'HighLatency', 'HighErrorRate', 'DbConnectionError', 'JobFailed', 'CapacityIssue', 'DependencyFailure')");

                            t.HasCheckConstraint("CK_Event_PayloadJson", "[PayloadJson] IS NULL OR ISJSON([PayloadJson]) = 1");

                            t.HasCheckConstraint("CK_Event_Severity", "[Severity] IN ('Info', 'Warning', 'Error', 'Critical')");
                        });
                });

            modelBuilder.Entity("incidenskezelo_backend.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Service", null, t =>
                        {
                            t.HasCheckConstraint("CK_Service_Kind", "[Kind] IN ('WebApp', 'Api', 'Database', 'Worker', 'External')");
                        });

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Code = "postgres-main",
                            IsActive = true,
                            Kind = "Database",
                            Name = "Main database"
                        },
                        new
                        {
                            ServiceId = 2,
                            Code = "orders-api",
                            IsActive = true,
                            Kind = "Api",
                            Name = "Orders API"
                        },
                        new
                        {
                            ServiceId = 3,
                            Code = "batch-worker",
                            IsActive = true,
                            Kind = "Worker",
                            Name = "Batch worker"
                        },
                        new
                        {
                            ServiceId = 4,
                            Code = "web-portal",
                            IsActive = true,
                            Kind = "WebApp",
                            Name = "Web portal"
                        },
                        new
                        {
                            ServiceId = 5,
                            Code = "file-ingest",
                            IsActive = true,
                            Kind = "Worker",
                            Name = "File ingest"
                        },
                        new
                        {
                            ServiceId = 6,
                            Code = "payment-gw",
                            IsActive = true,
                            Kind = "External",
                            Name = "Payment gateway"
                        });
                });

            modelBuilder.Entity("incidenskezelo_backend.Models.Event", b =>
                {
                    b.HasOne("incidenskezelo_backend.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
