services:
  db:
    ports:
      - "1433:1433" # Exposes database to host for local SQL inspection tools

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Overrides Production default
    ports:
      - "5000:8080" # Overrides 80:8080 with standard local dev port 5000