services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - net

  backend:
    build:
      context: ./incidenskezelo-backend/
    container_name: backend
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=IncidensKezelo;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - net

  frontend:
    build: 
      context: ./incidenskezelo-frontend/
    ports:
      - "80:80"
    networks:
      - net
    depends_on:
      - backend

networks:
  net:
    driver: bridge

volumes:
  db-data:
